import { Client, Invoice } from './types';

export const clients: Client[] = [
  { id: '1', name: 'Innovate Inc.', email: 'contact@innovate.com', avatarUrl: 'https://picsum.photos/seed/1/40/40' },
  { id: '2', name: 'Solutions Co.', email: 'hello@solutions.co', avatarUrl: 'https://picsum.photos/seed/2/40/40' },
  { id: '3', name: 'Apex Enterprises', email: 'support@apex.com', avatarUrl: 'https://picsum.photos/seed/3/40/40' },
  { id: '4', name: 'Quantum Dynamics', email: 'info@quantum.dev', avatarUrl: 'https://picsum.photos/seed/4/40/40' },
  { id: '5', name: 'Stellar Group', email: 'admin@stellar.org', avatarUrl: 'https://picsum.photos/seed/5/40/40' },
];

export const invoices: Invoice[] = [
  {
    id: 'INV001',
    clientId: '1',
    clientName: 'Innovate Inc.',
    clientEmail: 'contact@innovate.com',
    amount: 2500,
    issueDate: '2024-05-01',
    dueDate: '2024-06-01',
    status: 'paid',
    paymentDate: '2024-05-28',
  },
  {
    id: 'INV002',
    clientId: '2',
    clientName: 'Solutions Co.',
    clientEmail: 'hello@solutions.co',
    amount: 1500,
    issueDate: '2024-05-05',
    dueDate: '2024-06-05',
    status: 'pending',
    paymentDate: null,
  },
  {
    id: 'INV003',
    clientId: '3',
    clientName: 'Apex Enterprises',
    clientEmail: 'support@apex.com',
    amount: 3500,
    issueDate: '2024-04-10',
    dueDate: '2024-05-10',
    status: 'overdue',
    paymentDate: null,
  },
  {
    id: 'INV004',
    clientId: '4',
    clientName: 'Quantum Dynamics',
    clientEmail: 'info@quantum.dev',
    amount: 500,
    issueDate: '2024-05-15',
    dueDate: '2024-06-15',
    status: 'pending',
    paymentDate: null,
  },
  {
    id: 'INV005',
    clientId: '5',
    clientName: 'Stellar Group',
    clientEmail: 'admin@stellar.org',
    amount: 750,
    issueDate: '2024-05-20',
    dueDate: '2024-06-20',
    status: 'pending',
    paymentDate: null,
  },
  {
    id: 'INV006',
    clientId: '1',
    clientName: 'Innovate Inc.',
    clientEmail: 'contact@innovate.com',
    amount: 1800,
    issueDate: '2024-06-02',
    dueDate: '2024-07-02',
    status: 'pending',
    paymentDate: null,
  },
  {
    id: 'INV007',
    clientId: '2',
    clientName: 'Solutions Co.',
    clientEmail: 'hello@solutions.co',
    amount: 2200,
    issueDate: '2024-04-01',
    dueDate: '2024-05-01',
    status: 'paid',
    paymentDate: '2024-04-25',
  },
   {
    id: 'INV008',
    clientId: '3',
    clientName: 'Apex Enterprises',
    clientEmail: 'support@apex.com',
    amount: 4200,
    issueDate: '2024-06-10',
    dueDate: '2024-07-10',
    status: 'pending',
    paymentDate: null,
  },
  {
    id: 'INV009',
    clientId: '4',
    clientName: 'Quantum Dynamics',
    clientEmail: 'info@quantum.dev',
    amount: 600,
    issueDate: '2024-03-15',
    dueDate: '2024-04-15',
    status: 'overdue',
    paymentDate: null,
  },
  {
    id: 'INV010',
    clientId: '5',
    clientName: 'Stellar Group',
    clientEmail: 'admin@stellar.org',
    amount: 950,
    issueDate: '2024-02-20',
    dueDate: '2024-03-20',
    status: 'paid',
    paymentDate: '2024-03-18',
  },
];
